# Generated by Django 4.0.3 on 2022-03-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.IntegerField(primary_key=True, serialize=False)),
                ('articlecontent', models.CharField(max_length=200)),
                ('articlelike', models.IntegerField()),
                ('articlecomment', models.IntegerField()),
                ('articletime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('musicid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('musicname', models.CharField(max_length=200)),
                ('musicsinger', models.CharField(max_length=200)),
                ('musicalbum', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('information', models.CharField(default='周杰伦', max_length=200)),
                ('briefintroduction', models.CharField(default='这个人很懒，什么都没有留下', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayListCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistname', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistname', models.CharField(max_length=200)),
                ('playlistfounder', models.CharField(default='default', max_length=200)),
                ('musicid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.music')),
            ],
        ),
        migrations.CreateModel(
            name='MusicCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.music')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listentime', models.DateTimeField()),
                ('perception', models.CharField(max_length=200)),
                ('musicid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.music')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttime', models.DateTimeField()),
                ('commentcontent', models.CharField(max_length=200)),
                ('articleid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.article')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.user'),
        ),
    ]
