# Generated by Django 4.0.3 on 2022-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_article_articlecomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
