# Generated by Django 3.2.13 on 2022-05-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_imagetest_image2_alter_imagetest_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userimage',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
