# Generated by Django 3.2.13 on 2022-05-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_user_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlistimage',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
