# Generated by Django 3.2.13 on 2022-05-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20220511_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='musicid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='common.music'),
        ),
    ]
