# Generated by Django 3.2.13 on 2022-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20220526_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articlepic1',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articlepic2',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articlepic3',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
