# Generated by Django 4.0.3 on 2022-03-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articlecomment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='articlelike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='articletime',
            field=models.DateTimeField(default=0),
        ),
    ]
